name = "Polypack"
author = "hexagonelle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9edbbc3a5da67667d3e171024204bf7fb349bf39595b9faef42a6a9377bd6ad"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = "1.20"
datapack-folder = "config\\paxi\\datapacks"
no-internal-hashes = true
