name = "Polypack"
author = "hexagonelle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b7e5e1064df5d8e617306730ea0a05762b491b19a2438b10a6e68f6be8a6c6e"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
