name = "Polypack"
author = "hexagonelle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acfbef51e5b38e159f6cc80ba205c7e388bd93824142fe494161a477e323149f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = "1.20"
datapack-folder = "config\\paxi\\datapacks"
no-internal-hashes = true
